import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f8fa', // cor de fundo mais suave
  },
  container2: {
    padding: "4%",
    backgroundColor: '#f6f8fa',
  },
  header: {
    backgroundColor: '#003366',
    padding: 18,
    borderRadius: 16,
    marginBottom: 20,
    elevation: 4, // sombra Android
    shadowColor: '#000', // sombra iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  greeting: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  registro: {
    color: '#e0e0e0',
    fontSize: 13,
  },
  sistema: {
    color: '#e0e0e0',
    marginBottom: 8,
    fontSize: 14,
  },
  cardContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  card: {
    backgroundColor: '#4f8cff',
    padding: 10,
    borderRadius: 16,
    width: '30%',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#4f8cff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  card2: {
    backgroundColor: '#ff7a59',
    padding: 10,
    borderRadius: 16,
    marginLeft: 6,
    width: '30%',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#ff7a59',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  card3: {
    backgroundColor: '#43d19e',
    padding: 10,
    borderRadius: 16,
    marginLeft: 6,
    width: '30%',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#43d19e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  cardTitle: {
    fontWeight: 'bold',
    color: 'white',
    fontSize: 14,
    marginBottom: 4,
  },
  cardValue: {
    fontSize: 22,
    color: 'white',
    fontWeight: 'bold',
  },
  section: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
    color: '#003366',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  item: {
    padding: 10,
    borderRadius: 10,
    color: '#eaf0fa',
    fontWeight: '500',
    fontSize: 15,
  },
  date: {
    fontSize: 16,
    color: '#003366',
    fontWeight: 'bold',
    marginBottom: 6,
  },
  timeSlot: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  circle: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#4f8cff',
    marginRight: 12,
  },
  timeText: {
    fontSize: 15,
    color: '#003366',
    fontWeight: '500',
  },
  activity: {
    marginVertical: 5,
    color: '#003366',
    fontWeight: '500',
    fontSize: 15,
  },
  section2: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    borderRadius: 12,
    paddingHorizontal: 15,
    backgroundColor: '#fff',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  pendente: {
    backgroundColor: '#ff7a59',
    borderRadius: 8,
    alignItems: 'center',
    padding: 7,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 8,
    minWidth: 70,
  },
  buttonDisciplina: {
    backgroundColor: '#003366',
    borderRadius: 12,
    marginTop: 10,
    padding: 5,
    flexDirection: 'column',
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: '#003366',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.10,
    shadowRadius: 3,
  },
  itemDetalhe: {
    flexDirection: 'column',
    color: '#eaf0fa',
    borderRadius: 8,
    padding: 8,
    fontSize: 14,
  },
  separator: {
    height: 1,
    backgroundColor: '#d1d5db',
    marginVertical: 4,
  }
});

export default styles;
