import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f8fa',
  },
  content: {
    flex: 1,
  },
  contentHeader: {
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  title: {
    color: "#003366",
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  contentWarningTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#e59200",
    margin: 20,
    padding: 16,
    borderColor: "#ffb628",
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: "#fffbe6",
    textAlign: "left",
  },
  contentWarning: {
    fontWeight: "normal",
    fontSize: 15,
    color: "#e59200",
  },
  cards: {
    flex: 1,
    padding: 16,
    gap: 18,
  },
  cardsContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 10,
    elevation: 3,
    shadowColor: '#003366',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  cardsTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: '#003366',
    textAlign: 'left',
    flexShrink: 1,
  },
  cardsNotesApproved: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#43d19e',
    borderRadius: 20,
    color: 'white',
    overflow: 'hidden',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    minWidth: 50,
  },
  cardsNotesReproved: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#ff7a59',
    borderRadius: 20,
    color: 'white',
    overflow: 'hidden',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    minWidth: 50,
  },
  cardsNotesDefault: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#4f8cff',
    borderRadius: 20,
    color: 'white',
    overflow: 'hidden',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    minWidth: 50,
  },
});

export default styles;