import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f8fa',
  },
  content: {
    flex: 1,
  },
  contentHeader: {
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  title: {
    color: "#003366",
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  contentWarningTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#003366",
    margin: 20,
    padding: 16,
    borderColor: "#003366",
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: "#fff",
    textAlign: "left",
  },
  contentWarning: {
    fontWeight: "normal",
    fontSize: 15,
    color: "#003366",
  },
  cards: {
    flex: 1,
    padding: 16,
    gap: 18,
  },
  cardsContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 10,
    elevation: 3,
    shadowColor: '#003366',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  boletoCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: "#ccc",
    marginHorizontal: 20,
    marginBottom: 20,
    elevation: 3,
    shadowColor: '#003366',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    gap: 10,
  },
  boletoCardTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#003366",
  },
  boletoInfo: {
    fontSize: 14,
    color: "#444",
  },
  boletoValor: {
    fontSize: 24,
    color: "#e59200",
    fontWeight: "bold",
    marginTop: 8,
  },
  boletoVencimento: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  boletoBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: "#263fa3",
    borderRadius: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  boletoBadgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: 'bold',
  },
  boletoActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  boletoButtonDisabled: {
    backgroundColor: "#ccc",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
  },
  boletoButtonDisabledText: {
    color: "#888",
    fontWeight: "bold",
  },
  boletoDetailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
  },
  boletoDetailsItem: {
    flex: 1,
    alignItems: "flex-start",
  },
  boletoDetailsLabel: {
    fontSize: 12,
    color: "#666",
  },
  boletoDetailsValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#003366",
  },
});

export default styles;
