import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f8fa', // fundo suave igual Home
    marginBottom: 0,
  },
  content: {
    flex: 1,
  },
  title: {
    color: "#003366",
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  header: {
    backgroundColor: '#003366',
    borderRadius: 16,
    padding: 18,
    margin: 10,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
  },
  greeting: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  registro: {
    color: '#e0e0e0',
    fontSize: 13,
  },
  sistema: {
    color: '#e0e0e0',
    marginBottom: 8,
    fontSize: 14,
  },
  cards: {
    flex: 1,
    padding: 16,
    gap: 18,
  },
  cardsContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 10,
    elevation: 3,
    shadowColor: '#003366',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  cardsTitle: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#003366',
    textAlign: 'left',
    flexShrink: 1,
  },
  cardsNotesApproved: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#43d19e',
    borderRadius: 20,
    color: 'white',
    overflow: 'hidden',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    minWidth: 50,
  },
  cardsNotesReproved: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#ff7a59',
    borderRadius: 20,
    color: 'white',
    overflow: 'hidden',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    minWidth: 50,
  },
  cardsNotesDefault: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#4f8cff',
    borderRadius: 20,
    color: 'white',
    overflow: 'hidden',
    fontWeight: 'bold',
    fontSize: 14,
    textAlign: 'center',
    minWidth: 50,
  },
  accordionContainer: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    marginVertical: 6,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  details: {
    padding: 16,
    backgroundColor: '#eaf0fa',
    borderRadius: 10,
    marginTop: 8,
  },
  legendaContainer: {
    marginTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    backgroundColor: '#fff',
    borderRadius: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 3,
  },
  legendaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  legendaBola: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  legendaTexto: {
    fontSize: 14,
    color: '#003366',
    fontWeight: '500',
  },
  tituloPag: {
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
  },
  titulo: {
    color: "#003366",
    fontSize: 30,
    fontWeight: 'bold',
  }
});

export default styles;
